// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTb6oEI6TU3Q9H2IwjIrEw19v1dRsBAI',
    appId: '1:1025014149435:web:3b35a99970efd05f45871e',
    messagingSenderId: '1025014149435',
    projectId: 'truckpark-share',
    authDomain: 'truckpark-share.firebaseapp.com',
    storageBucket: 'truckpark-share.firebasestorage.app',
    measurementId: 'G-5BYP9PWLBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfx_nK7C3anP5Fth2OjQLivtFY-VZkVs',
    appId: '1:1025014149435:android:c457943153b36d7845871e',
    messagingSenderId: '1025014149435',
    projectId: 'truckpark-share',
    storageBucket: 'truckpark-share.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqvVDRJvfT-AGbwvUC6Wq9Gk3_Kf_znY',
    appId: '1:1025014149435:ios:2b32af47cccfc19f45871e',
    messagingSenderId: '1025014149435',
    projectId: 'truckpark-share',
    storageBucket: 'truckpark-share.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
