import 'app_language.dart';

const supportedLanguages = [
  AppLanguage(
    languageCode: 'bg',
    nativeName: 'Български',
    englishName: 'Bulgarian',
    countryCode: 'BG',
  ),
  AppLanguage(
    languageCode: 'hr',
    nativeName: 'Hrvatski',
    englishName: 'Croatian',
    countryCode: 'HR',
  ),
  AppLanguage(
    languageCode: 'cs',
    nativeName: 'Čeština',
    englishName: 'Czech',
    countryCode: 'CZ',
  ),
  AppLanguage(
    languageCode: 'da',
    nativeName: 'Dansk',
    englishName: 'Danish',
    countryCode: 'DK',
  ),
  AppLanguage(
    languageCode: 'nl',
    nativeName: 'Nederlands',
    englishName: 'Dutch',
    countryCode: 'NL',
  ),
  AppLanguage(
    languageCode: 'en',
    nativeName: 'English',
    englishName: 'English',
    countryCode: 'GB',
  ),
  AppLanguage(
    languageCode: 'et',
    nativeName: 'Eesti',
    englishName: 'Estonian',
    countryCode: 'EE',
  ),
  AppLanguage(
    languageCode: 'fi',
    nativeName: 'Suomi',
    englishName: 'Finnish',
    countryCode: 'FI',
  ),
  AppLanguage(
    languageCode: 'fr',
    nativeName: 'Français',
    englishName: 'French',
    countryCode: 'FR',
  ),
  AppLanguage(
    languageCode: 'de',
    nativeName: 'Deutsch',
    englishName: 'German',
    countryCode: 'DE',
  ),
  AppLanguage(
    languageCode: 'el',
    nativeName: 'Ελληνικά',
    englishName: 'Greek',
    countryCode: 'GR',
  ),
  AppLanguage(
    languageCode: 'hu',
    nativeName: 'Magyar',
    englishName: 'Hungarian',
    countryCode: 'HU',
  ),
  AppLanguage(
    languageCode: 'ga',
    nativeName: 'Gaeilge',
    englishName: 'Irish',
    countryCode: 'IE',
  ),
  AppLanguage(
    languageCode: 'it',
    nativeName: 'Italiano',
    englishName: 'Italian',
    countryCode: 'IT',
  ),
  AppLanguage(
    languageCode: 'lv',
    nativeName: 'Latviešu',
    englishName: 'Latvian',
    countryCode: 'LV',
  ),
  AppLanguage(
    languageCode: 'lt',
    nativeName: 'Lietuvių',
    englishName: 'Lithuanian',
    countryCode: 'LT',
  ),
  AppLanguage(
    languageCode: 'mt',
    nativeName: 'Malti',
    englishName: 'Maltese',
    countryCode: 'MT',
  ),
  AppLanguage(
    languageCode: 'pl',
    nativeName: 'Polski',
    englishName: 'Polish',
    countryCode: 'PL',
  ),
  AppLanguage(
    languageCode: 'pt',
    nativeName: 'Português',
    englishName: 'Portuguese',
    countryCode: 'PT',
  ),
  AppLanguage(
    languageCode: 'ro',
    nativeName: 'Română',
    englishName: 'Romanian',
    countryCode: 'RO',
  ),
  AppLanguage(
    languageCode: 'sk',
    nativeName: 'Slovenčina',
    englishName: 'Slovak',
    countryCode: 'SK',
  ),
  AppLanguage(
    languageCode: 'sl',
    nativeName: 'Slovenščina',
    englishName: 'Slovenian',
    countryCode: 'SI',
  ),
  AppLanguage(
    languageCode: 'es',
    nativeName: 'Español',
    englishName: 'Spanish',
    countryCode: 'ES',
  ),
  AppLanguage(
    languageCode: 'sv',
    nativeName: 'Svenska',
    englishName: 'Swedish',
    countryCode: 'SE',
  ),
  AppLanguage(
    languageCode: 'ru',
    nativeName: 'Русский',
    englishName: 'Russian',
    countryCode: 'RU',
  ),
  AppLanguage(
    languageCode: 'tr',
    nativeName: 'Türkçe',
    englishName: 'Turkish',
    countryCode: 'TR',
  ),
  AppLanguage(
  languageCode: 'ar',
  nativeName: 'العربية',
  englishName: 'Arabic',
  countryCode: 'SA',
),
];